apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    import json
    import requests
    from locust import HttpUser, between, task


    class LunaticERPUser(HttpUser):
        wait_time = between(5, 15)
        @task
        def pageRetrieve(self):
            self.client.get("/api/transport/out/material/request/list?current=1&pageSize=20")
            
